# Generated by Django 2.0.1 on 2018-02-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_userprofile_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='合同名称')),
                ('template', models.TextField()),
            ],
        ),
    ]
