# Generated by Django 2.0.1 on 2018-02-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180209_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='homework_title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
